import { SceneRow } from '../types'

export const mockScenes: SceneRow[] = [
    {
        id: 'BillyScrubs|BJ01',
        name: 'Blowjob 01',
        modpack: 'BillyScrubs',
        actorCount: 2,
        furnitureType: '',
        tags: ['oral', 'kneeling'],
        actions: [
            { type: 'blowjob',   actor: 0, target: 1, performer: 0 },
            { type: 'handjob',   actor: 0, target: 1, performer: 0 },
        ],
        actors: [
            { intendedSex: 'female', tags: ['submissive'] },
            { intendedSex: 'male',   tags: ['dominant'] },
        ],
        isTransition: false,
        noRandomSelection: false,
    },
    {
        id: 'BillyScrubs|BJ01_Swapped',
        name: 'Blowjob 01 (Swapped)',
        modpack: 'BillyScrubs',
        actorCount: 2,
        furnitureType: '',
        tags: ['oral'],
        actions: [{ type: 'blowjob', actor: 0, target: 1, performer: 0 }],
        actors: [
            { intendedSex: 'male',   tags: [] },
            { intendedSex: 'female', tags: [] },
        ],
        isTransition: false,
        noRandomSelection: false,
    },
    {
        id: 'BillyScrubs|Missionary01',
        name: 'Missionary 01',
        modpack: 'BillyScrubs',
        actorCount: 2,
        furnitureType: '',
        tags: ['vaginal', 'missionary', 'vanilla'],
        actions: [
            { type: 'vaginal',   actor: 1, target: 0, performer: 1 },
            { type: 'caress',    actor: 1, target: 0, performer: 1 },
        ],
        actors: [
            { intendedSex: 'female', tags: ['submissive', 'lying'] },
            { intendedSex: 'male',   tags: ['dominant'] },
        ],
        isTransition: false,
        noRandomSelection: false,
    },
    {
        id: 'BillyScrubs|Missionary01_to_Cowgirl_Trans',
        name: 'Missionary → Cowgirl Transition',
        modpack: 'BillyScrubs',
        actorCount: 2,
        furnitureType: '',
        tags: ['vaginal', 'transition'],
        actions: [{ type: 'vaginal', actor: 1, target: 0, performer: 1 }],
        actors: [
            { intendedSex: 'female', tags: [] },
            { intendedSex: 'male',   tags: [] },
        ],
        isTransition: true,
        noRandomSelection: true,
    },
    {
        id: 'SomePack|ThreesomeMFF01',
        name: 'Threesome MFF 01',
        modpack: 'SomePack',
        actorCount: 3,
        furnitureType: '',
        tags: ['threesome', 'vaginal', 'oral'],
        actions: [
            { type: 'vaginal',   actor: 2, target: 0, performer: 2 },
            { type: 'oral',      actor: 1, target: 0, performer: 1 },
        ],
        actors: [
            { intendedSex: 'female', tags: ['submissive'] },
            { intendedSex: 'female', tags: ['dominant'] },
            { intendedSex: 'male',   tags: ['dominant'] },
        ],
        isTransition: false,
        noRandomSelection: false,
    },
    {
        id: 'SomePack|BedScene01',
        name: 'Bed Scene 01',
        modpack: 'SomePack',
        actorCount: 2,
        furnitureType: 'bed',
        tags: ['vaginal', 'bed', 'cuddling'],
        actions: [
            { type: 'vaginal', actor: 1, target: 0, performer: 1 },
            { type: 'caress',  actor: 1, target: 0, performer: 1 },
        ],
        actors: [
            { intendedSex: 'female', tags: ['lying', 'submissive'] },
            { intendedSex: 'male',   tags: ['lying', 'dominant'] },
        ],
        isTransition: false,
        noRandomSelection: false,
    },
    {
        id: 'SomePack|ChairScene01',
        name: 'Chair Scene 01',
        modpack: 'SomePack',
        actorCount: 2,
        furnitureType: 'chair',
        tags: ['oral', 'sitting'],
        actions: [
            { type: 'blowjob', actor: 0, target: 1, performer: 0 },
        ],
        actors: [
            { intendedSex: 'female', tags: ['kneeling'] },
            { intendedSex: 'male',   tags: ['sitting'] },
        ],
        isTransition: false,
        noRandomSelection: false,
    },
    {
        id: 'SomePack|ChairScene02',
        name: 'Chair Scene 02',
        modpack: 'SomePack',
        actorCount: 2,
        furnitureType: 'chair',
        tags: ['oral', 'sitting'],
        actions: [
            { type: 'blowjob', actor: 0, target: 1, performer: 0 },
        ],
        actors: [
            { intendedSex: 'female', tags: ['kneeling'] },
            { intendedSex: 'male',   tags: ['sitting'] },
        ],
        isTransition: false,
        noRandomSelection: false,
    },
    {
        id: 'SomePack|ChairScene03',
        name: 'Chair Scene 03',
        modpack: 'SomePack',
        actorCount: 2,
        furnitureType: 'chair',
        tags: ['oral', 'sitting'],
        actions: [
            { type: 'blowjob', actor: 0, target: 1, performer: 0 },
        ],
        actors: [
            { intendedSex: 'female', tags: ['kneeling'] },
            { intendedSex: 'male',   tags: ['sitting'] },
        ],
        isTransition: false,
        noRandomSelection: false,
    },
    {
        id: 'AnotherPack|HandjobStanding01',
        name: 'Handjob Standing 01',
        modpack: 'AnotherPack',
        actorCount: 2,
        furnitureType: '',
        tags: ['handjob', 'standing', 'clothed'],
        actions: [
            { type: 'handjob', actor: 0, target: 1, performer: 0 },
        ],
        actors: [
            { intendedSex: 'female', tags: ['standing'] },
            { intendedSex: 'male',   tags: ['standing'] },
        ],
        isTransition: false,
        noRandomSelection: false,
    },
    {
        id: 'AnotherPack|Doggy01',
        name: 'Doggy Style 01',
        modpack: 'AnotherPack',
        actorCount: 2,
        furnitureType: '',
        tags: ['vaginal', 'doggy', 'rough'],
        actions: [
            { type: 'vaginal', actor: 1, target: 0, performer: 1 },
            { type: 'spank',   actor: 1, target: 0, performer: 1 },
        ],
        actors: [
            { intendedSex: 'female', tags: ['submissive', 'doggy'] },
            { intendedSex: 'male',   tags: ['dominant', 'standing'] },
        ],
        isTransition: false,
        noRandomSelection: false,
    },
    {
        id: 'AnotherPack|Cowgirl01',
        name: 'Cowgirl 01',
        modpack: 'AnotherPack',
        actorCount: 2,
        furnitureType: '',
        tags: ['vaginal', 'cowgirl', 'riding'],
        actions: [
            { type: 'vaginal', actor: 0, target: 1, performer: 0 },
        ],
        actors: [
            { intendedSex: 'female', tags: ['dominant', 'riding'] },
            { intendedSex: 'male',   tags: ['submissive', 'lying'] },
        ],
        isTransition: false,
        noRandomSelection: false,
    },
]
